#!/bin/bash

#   get-node-ip - Get the IP address of a VM managed by virsh.

#   Copyright 2018-2023 Earl C. Ruby III
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

usage()
{
cat << EOF
usage: $0 hostname [iface]

This script will take a virsh-managed VM hostname and return the IP address. In the case of using the network in the `bridge` mode,
the arp table will not possibly contain any IP addresses, optionally use alternative method `arp-scan` on specified `iface`.
EOF
}

HOSTNAME=$1
IFACE=$2

if [[ -z $HOSTNAME ]]; then
    echo "ERROR: Hostname is required"
    usage
    exit 1
fi

MAC=$(virsh -q domiflist $HOSTNAME | awk '{ print $5 }')

if [[ -z ${IFACE}  ]]; then
  arp -e | grep -i $MAC | awk '{ print $1 }'
else
  arp-scan --interface ${IFACE} --localnet | grep -i $MAC | awk '{ print $1 }'
fi
